name: Nuget - $(Date:yyyy.MM.dd).$(BuildID)

pr: none

resources:
  repositories:
    - repository: Krosoft.Extensions
      type: github
      name: krosoft-dev/Krosoft.Extensions
      endpoint: krosoft-dev
trigger: none

pool:
  vmImage: "ubuntu-latest"

variables:
  pipelineFilter: "nuget - Krosoft"

stages:
  - stage: Run
    displayName: Run
    jobs:
      - job: Run
        steps:
          # - bash: az --version
          #   displayName: "Show Azure CLI version"

          - bash: echo ${AZURE_DEVOPS_CLI_PAT} | az devops login
            env:
              AZURE_DEVOPS_CLI_PAT: $(System.AccessToken)
            displayName: "Login Azure DevOps Extension"

          - bash: |
              az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject) --use-git-aliases true
            displayName: "Set default Azure DevOps organization and project"

          # - bash: |
          #     az pipelines list --org $(System.CollectionUri) --project $(System.TeamProject)
          #   displayName: "Show pipeline list"

          - bash: |
              pipelines=$(az pipelines list --query "[?starts_with(name,'$(pipelineFilter)')].{Name:name, Id:id}" -o json)


              # Initialisation du compteur d'index
              index=0

              # Boucle sur les pipelines
              for pipeline in $(echo "$pipelines" | jq -r '.[] | @base64'); do
                _jq() {
                    echo ${pipeline} | base64 --decode | jq -r ${1}
                }

                pipelineName=$(_jq '.Name')
                pipelineId=$(_jq '.Id')

                 # Incrémenter l'index à chaque itération
                ((index++))

                echo "Run '$pipelineName'. (Pipeline $index of $(echo "$pipelines" | jq -r 'length'))"
                
                # Déclencher la pipeline
                result=$(az pipelines run --org $(System.CollectionUri) --project $(System.TeamProject) --id $pipelineId -o json)

                # Extraire l'ID de la réponse
                resultId=$(echo "$result" | jq -r '.id')

                echo "With id '$resultId'"
                echo ""
              done
            displayName: Run
